// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thanachart_test.Data;

#nullable disable

namespace Thanachart_test.Migrations
{
    [DbContext(typeof(ShoppingDbContext))]
    partial class ShoppingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Thanachart_test.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Thanachart_test.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Quantity] * [UnitPrice]", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductCode");

                    b.ToTable("OrderDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderDetails_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("Thanachart_test.Models.Product", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Code");

                    b.ToTable("Product", null, t =>
                        {
                            t.HasCheckConstraint("CK_Product_UnitPrice_NonNegative", "[UnitPrice] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Code = "P001",
                            ProductName = "โน้ตบุ๊ก ThinkPad X1 Carbon",
                            UnitPrice = 45900.00m
                        },
                        new
                        {
                            Code = "P002",
                            ProductName = "เมาส์ไร้สาย Logitech MX Master 3S",
                            UnitPrice = 3290.50m
                        },
                        new
                        {
                            Code = "P003",
                            ProductName = "คีย์บอร์ด Keychron K2 (Hot-swap)",
                            UnitPrice = 3890.00m
                        },
                        new
                        {
                            Code = "P004",
                            ProductName = "จอมอนิเตอร์ Dell 27\" 4K",
                            UnitPrice = 15900.00m
                        },
                        new
                        {
                            Code = "P005",
                            ProductName = "หูฟัง Sony WH-1000XM5",
                            UnitPrice = 12990.75m
                        },
                        new
                        {
                            Code = "P006",
                            ProductName = "เว็บแคม Logitech C920",
                            UnitPrice = 2490.00m
                        },
                        new
                        {
                            Code = "P007",
                            ProductName = "SSD Samsung 990 Pro 1TB",
                            UnitPrice = 4590.25m
                        },
                        new
                        {
                            Code = "P008",
                            ProductName = "แรม Corsair DDR5 32GB",
                            UnitPrice = 4290.00m
                        },
                        new
                        {
                            Code = "P009",
                            ProductName = "การ์ดจอ RTX 4090 (ของหมด)",
                            UnitPrice = 89900.00m
                        },
                        new
                        {
                            Code = "P010",
                            ProductName = "ด็อกกิ้ง Thunderbolt 4 (เหลือน้อย)",
                            UnitPrice = 8990.00m
                        },
                        new
                        {
                            Code = "P011",
                            ProductName = "สาย USB-C to USB-C 1m",
                            UnitPrice = 199.99m
                        },
                        new
                        {
                            Code = "P012",
                            ProductName = "แผ่นรองเมาส์ ขนาดใหญ่",
                            UnitPrice = 350.50m
                        });
                });

            modelBuilder.Entity("Thanachart_test.Models.Stock", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Stock", null, t =>
                        {
                            t.HasCheckConstraint("CK_Stock_Quantity_NonNegative", "[StockQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Code = "P001",
                            StockQuantity = 12
                        },
                        new
                        {
                            Code = "P002",
                            StockQuantity = 40
                        },
                        new
                        {
                            Code = "P003",
                            StockQuantity = 25
                        },
                        new
                        {
                            Code = "P004",
                            StockQuantity = 8
                        },
                        new
                        {
                            Code = "P005",
                            StockQuantity = 15
                        },
                        new
                        {
                            Code = "P006",
                            StockQuantity = 30
                        },
                        new
                        {
                            Code = "P007",
                            StockQuantity = 50
                        },
                        new
                        {
                            Code = "P008",
                            StockQuantity = 20
                        },
                        new
                        {
                            Code = "P009",
                            StockQuantity = 0
                        },
                        new
                        {
                            Code = "P010",
                            StockQuantity = 3
                        },
                        new
                        {
                            Code = "P011",
                            StockQuantity = 200
                        },
                        new
                        {
                            Code = "P012",
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("Thanachart_test.Models.StockTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("ChangeAmount")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TransactionId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductCode");

                    b.ToTable("StockTransaction", (string)null);

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            ChangeAmount = 12,
                            ProductCode = "P001",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        },
                        new
                        {
                            TransactionId = 2,
                            ChangeAmount = 40,
                            ProductCode = "P002",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        },
                        new
                        {
                            TransactionId = 3,
                            ChangeAmount = 25,
                            ProductCode = "P003",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        },
                        new
                        {
                            TransactionId = 4,
                            ChangeAmount = 8,
                            ProductCode = "P004",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        },
                        new
                        {
                            TransactionId = 5,
                            ChangeAmount = 15,
                            ProductCode = "P005",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        },
                        new
                        {
                            TransactionId = 6,
                            ChangeAmount = 30,
                            ProductCode = "P006",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        },
                        new
                        {
                            TransactionId = 7,
                            ChangeAmount = 50,
                            ProductCode = "P007",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        },
                        new
                        {
                            TransactionId = 8,
                            ChangeAmount = 20,
                            ProductCode = "P008",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        },
                        new
                        {
                            TransactionId = 9,
                            ChangeAmount = 0,
                            ProductCode = "P009",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        },
                        new
                        {
                            TransactionId = 10,
                            ChangeAmount = 3,
                            ProductCode = "P010",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        },
                        new
                        {
                            TransactionId = 11,
                            ChangeAmount = 200,
                            ProductCode = "P011",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        },
                        new
                        {
                            TransactionId = 12,
                            ChangeAmount = 100,
                            ProductCode = "P012",
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Seed"
                        });
                });

            modelBuilder.Entity("Thanachart_test.Models.OrderDetail", b =>
                {
                    b.HasOne("Thanachart_test.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thanachart_test.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Thanachart_test.Models.Stock", b =>
                {
                    b.HasOne("Thanachart_test.Models.Product", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("Thanachart_test.Models.Stock", "Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Thanachart_test.Models.StockTransaction", b =>
                {
                    b.HasOne("Thanachart_test.Models.Order", "Order")
                        .WithMany("StockTransactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thanachart_test.Models.Product", "Product")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Thanachart_test.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("Thanachart_test.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Stock");

                    b.Navigation("StockTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
